baseURL = 'https://chesterheng.github.io/hugo-blogapp/'
languageCode = 'en-us'
title = 'Lama dev blog'

paginate = 1

[params]
  description = "The fastest blog"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"